{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "podinfo.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
{{- end -}}
